default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123456
  timeout: 5000

development:
  <<: *default
  database: dashboard
test:
  <<: *default
  database: dashboard

production:
  <<: *default
  database: dashboard